# Generated by Django 3.2.7 on 2021-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_topic_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
